global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent1'
    scrape_interval: 10s
    static_configs:
      - targets: ['agent1:4567']
    relabel_configs:
      - target_label: host
        replacement: agent1
      - target_label: location
        replacement: iutnc-503-04

  - job_name: 'agent2'
    scrape_interval: 10s
    static_configs:
      - targets: ['agent2:4568']
    relabel_configs:
      - target_label: host
        replacement: agent2
      - target_label: location
        replacement: iutnc-503-04-backup