global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'agent_ruby'
    static_configs:
      - targets: ['agent1:4567']
        labels:
          host: 'audit_ruby'

